apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: ci

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  test:
    steps:
      - name: Check out source code
        uses: cloudbees-io/checkout@v1

      - name: Run tests and publish results
        uses: ./.cloudbees/actions/run-tests
        with:
          working-directory: "."

      - name: Publish test evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Test job summary
            - Run ID: ${{ cloudbees.run_id }}
            - Branch: ${{ cloudbees.scm.branch }}
            - Commit: ${{ cloudbees.scm.sha }}

  build:
    needs:
      - test
    steps:
      - name: Check out source code
        uses: cloudbees-io/checkout@v1

      - name: Configure Docker Hub credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: index.docker.io
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push with Kaniko
        id: kaniko-build
        uses: cloudbees-io/kaniko@v1
        kind: build
        with:
          destination: ${{ vars.DOCKER_USERNAME }}/banking-app:${{ cloudbees.scm.sha }},${{ vars.DOCKER_USERNAME }}/banking-app:latest
          dockerfile: Dockerfile
          verbosity: info

      - name: Publish build evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Build summary
            - Image: `${{ vars.DOCKER_USERNAME }}/banking-app:latest`
            - Commit SHA: `${{ cloudbees.scm.sha }}`
            - Run ID: ${{ cloudbees.run_id }}
            - Digest: ${{ steps.kaniko-build.outputs.digest }}
