apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: ci

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  test:
    steps:
      - name: Check out source code
        uses: cloudbees-io/checkout@v1

      - name: Run tests and publish results
        uses: ./.cloudbees/actions/run-tests
        with:
          working-directory: "."

      - name: Publish test evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Test job summary
            - Run ID: ${{ cloudbees.run_id }}
            - Branch: ${{ cloudbees.scm.branch }}
            - Commit: ${{ cloudbees.scm.sha }}

  build:
    needs:
      - test
    uses: ./.cloudbees/workflows/reusable-build.yaml
    secrets: inherit
