apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: reusable-build

on:
  workflow_call:
    inputs:
      image-name:
        type: string
        required: true
        description: Docker Hub image name
      image-tag:
        type: string
        required: false
        default: latest
        description: Docker image tag
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        required: false
        default: latest
        description: Docker image tag

jobs:
  build-and-push:
    steps:
      - name: Check out source code
        uses: cloudbees-io/checkout@v1

      - name: Configure Docker Hub credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: index.docker.io
          username: tejasdesai27
          password: ${{ actionsecrets.docker_token }}

      - name: Build and push with Kaniko
        id: kaniko-build
        uses: cloudbees-io/kaniko@v1
        kind: build
        with:
          destination: tejasdesai27/banking-app:${{ inputs.image-tag }},tejasdesai27/banking-app:latest
          dockerfile: Dockerfile
          verbosity: info

      - name: Publish build evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Build summary
            - Image: `tejasdesai27/banking-app:${{ inputs.image-tag }}`
            - Run ID: ${{ cloudbees.run_id }}
            - Digest: ${{ steps.kaniko-build.outputs.digest }}
